### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by RajahBimmy** [RajahBimmy/Sungear-Port#9]
Use PHP to handle user I/O when uploading their own data to be simulated. We should take the data and build it into an array of objects which are serialized into JSON format before being passed to the Javascript. Will work on this implementation tonight.

**Comment by RajahBimmy** [comment]
Wait we should totally use C#

**Comment by RajahBimmy** [comment]
Lol nvm we absolutely shouldn't

**Comment by dns-mcdaid** [comment]
node pls
